name: OmniChat
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  Markdown:
    url: https://github.com/apple/swift-markdown
    from: "0.7.0"
  Splash:
    url: https://github.com/JohnSundell/Splash
    from: "0.16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    PRODUCT_NAME: OmniChat
    DEVELOPMENT_LANGUAGE: en
    ENABLE_USER_SCRIPT_SANDBOXING: false
  release:
    SWIFT_OPTIMIZATION_LEVEL: -O

targets:
  OmniChat:
    type: application
    platform: [iOS, macOS]
    sources:
      - OmniChat
    dependencies: []
    settings:
      base:
        INFOPLIST_FILE: OmniChat/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.omnichat
        CODE_SIGN_ENTITLEMENTS: OmniChat/OmniChat.entitlements
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0"
        # SwiftData support
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        # macOS-specific
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
    entitlements:
      path: OmniChat/OmniChat.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.yourname.omnichat
        com.apple.developer.icloud-services:
          - CloudKit
          - Key-value-store
        com.apple.security.application-groups:
          - group.com.yourname.omnichat.shared
        # macOS Sandbox
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-only: true
    info:
      path: OmniChat/Info.plist
      properties:
        CFBundleDisplayName: OmniChat
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: AccentColor
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        NSSupportsAutomaticTermination: true
        NSSupportsSuddenTermination: true
        NSHumanReadableCopyright: "Copyright 2026. All rights reserved."

  OmniChatTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources:
      - OmniChatTests
    dependencies:
      - target: OmniChat_iOS
        platforms: [iOS]
      - target: OmniChat_macOS
        platforms: [macOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.omnichat.tests
        # Enable both Swift Testing and XCTest
        CLANG_ENABLE_MODULES: YES
        GENERATE_INFOPLIST_FILE: YES

  OmniChatUITests:
    type: bundle.ui-testing
    platform: [iOS, macOS]
    sources:
      - OmniChatUITests
    dependencies:
      - target: OmniChat_iOS
        platforms: [iOS]
      - target: OmniChat_macOS
        platforms: [macOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.omnichat.uitests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  OmniChat:
    build:
      targets:
        OmniChat_iOS: all
        OmniChat_macOS: all
    run:
      config: Debug
    archive:
      config: Release
  OmniChatTests:
    build:
      targets:
        OmniChatTests_iOS: all
        OmniChatTests_macOS: all
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - OmniChatTests_iOS
        - OmniChatTests_macOS
